services:
  ts-meo-discord:
    build: .
    container_name: ts-meo-discord
    volumes:
      - .:/ts-meo-discord
    environment:
      - NODE_ENV=production  # 本番環境を指定
    command: ["bun", "src/index.ts"]  # 本番用の実行コマンド
    restart: unless-stopped
